const { withXcodeProject } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// This has to be a config plugin (not a one-off manual edit) because
// `ios/` is regenerated by `expo prebuild` on every build.
const TARGET_FILE = 'ShareExtension/ShareViewController.swift';
const INFO_PLIST_FILE = 'ShareExtension/ShareExtension-Info.plist';

// What the extension is called in the iOS share sheet. Set here rather than
// through expo-share-intent's `iosShareExtensionName`, which also renames the
// native target and its folder — a structural change that would break this
// plugin's file paths and shift the extension's bundle identifier. Rewriting
// just the display string leaves the target exactly as it was.
const SHARE_SHEET_NAME = 'Chiaro';

const PATCHES = [
  {
    // Some apps (WhatsApp's forward arrow, Notes, Mail) hand a shared
    // message to the extension via `NSExtensionItem.attributedContentText`
    // with an *empty* `attachments` array, instead of an item conforming to
    // `public.text`/`public.plain-text`/`public.utf8-plain-text`. The
    // upstream template only ever looks at `attachments`, so those shares
    // silently do nothing — the extension just sits there.
    name: 'attributed-content-text-fallback',
    oldBlock: `      else {
        dismissWithError(message: "No content found")
        return
      }
      for (index, attachment) in (attachments).enumerated() {`,
    newBlock: `      else {
        dismissWithError(message: "No content found")
        return
      }

      if attachments.isEmpty, let plainText = content.attributedContentText?.string,
        !plainText.isEmpty
      {
        // Must hop onto the main actor before doing any of this: the
        // enclosing Task is not main-actor isolated, and redirectToHostApp
        // walks the responder chain and calls canOpenURL/openURL — all
        // UIKit, all main-thread-only. Running it off-thread crashes the app
        // that presented the share sheet. Every other handler in this file
        // hops first for exactly this reason; see handleText.
        Task { @MainActor in
          self.sharedText.append(plainText)
          let userDefaults = UserDefaults(suiteName: self.hostAppGroupIdentifier)
          userDefaults?.set(self.sharedText, forKey: self.sharedKey)
          userDefaults?.synchronize()
          self.redirectToHostApp(type: .text)
        }
        return
      }

      for (index, attachment) in (attachments).enumerated() {`,
  },
  {
    // expo-share-intent hands the payload to the app through the App Group
    // shared container. That transport depends on the
    // `com.apple.security.application-groups` entitlement actually being
    // granted at runtime — and when it isn't, `UserDefaults(suiteName:)`
    // returns nil and every write goes through `?.`, so the payload is
    // dropped in complete silence: the app still launches, just with nothing
    // to import. Text and link shares are small enough to travel inside the
    // redirect URL itself, which needs no entitlement at all.
    name: 'inline-url-payload',
    oldBlock: `  private func redirectToHostApp(type: RedirectType) {
    let nonce = UUID().uuidString
    let url = URL(string: "\\(shareProtocol)://dataUrl=\\(sharedKey)?nonce=\\(nonce)#\\(type)")!
    var responder = self as UIResponder?`,
    newBlock: `  /// Builds a \`smartflow://process?text=…\` / \`smartflow://extract-url?url=…\`
  /// URL carrying the shared payload directly, so it survives even when the
  /// App Group container isn't available. Returns nil for share kinds that
  /// can't travel in a URL (media, files) or payloads too large to try.
  /// Both routes are already handled app-side by useIncomingShareIntent.
  private func inlineRedirectUrl(type: RedirectType) -> URL? {
    let payload: String
    let route: String
    switch type {
    case .text:
      payload = sharedText.joined(separator: "\\n")
      route = "process?text="
    case .weburl:
      payload = sharedWebUrl.first?.url ?? ""
      route = "extract-url?url="
    default:
      return nil
    }

    var allowed = CharacterSet.alphanumerics
    allowed.insert(charactersIn: "-._~")

    guard !payload.isEmpty,
      let encoded = payload.addingPercentEncoding(withAllowedCharacters: allowed),
      // Stay well clear of the practical ceiling on a URL handed to openURL;
      // anything longer falls back to the App Group path below.
      encoded.count <= 8000
    else {
      return nil
    }
    return URL(string: "\\(shareProtocol)://\\(route)\\(encoded)")
  }

  private func redirectToHostApp(type: RedirectType) {
    let nonce = UUID().uuidString
    let url =
      inlineRedirectUrl(type: type)
      ?? URL(string: "\\(shareProtocol)://dataUrl=\\(sharedKey)?nonce=\\(nonce)#\\(type)")!
    var responder = self as UIResponder?`,
  },
];

// expo-share-intent writes ShareViewController.swift from a `withXcodeProject`
// mod, not a `withDangerousMod` — those run in a different, earlier phase of
// the prebuild pipeline, so a dangerousMod here would run *before* the file
// even exists. Using the same mod type, registered after expo-share-intent
// in app.json's plugin list, guarantees this runs afterward instead.
function withShareExtensionFix(config) {
  return withXcodeProject(config, async (config) => {
    const filePath = path.join(config.modRequest.platformProjectRoot, TARGET_FILE);
    if (!fs.existsSync(filePath)) {
      throw new Error(
        `[withShareExtensionFix] Expected file not found: ${filePath}. Did expo-share-intent's ` +
          'generated file layout change? Update this plugin to match.',
      );
    }

    let source = fs.readFileSync(filePath, 'utf8');

    for (const patch of PATCHES) {
      if (source.includes(patch.newBlock)) {
        continue; // already patched (e.g. prebuild ran twice)
      }
      if (!source.includes(patch.oldBlock)) {
        throw new Error(
          `[withShareExtensionFix] Patch "${patch.name}" could not find its expected source in ` +
            `${TARGET_FILE} — expo-share-intent's template likely changed. Update ` +
            'plugins/withShareExtensionFix.js to match the new source before this fix can apply.',
        );
      }
      source = source.replace(patch.oldBlock, patch.newBlock);
    }

    fs.writeFileSync(filePath, source);

    renameShareSheetEntry(config.modRequest.platformProjectRoot);
    return config;
  });
}

/**
 * Replaces the extension's `CFBundleDisplayName` — the label iOS shows in the
 * share sheet, which upstream generates as "<app name> - Share Extension".
 */
function renameShareSheetEntry(platformProjectRoot) {
  const plistPath = path.join(platformProjectRoot, INFO_PLIST_FILE);
  if (!fs.existsSync(plistPath)) {
    throw new Error(
      `[withShareExtensionFix] Expected file not found: ${plistPath}. Did expo-share-intent's ` +
        'generated file layout change? Update this plugin to match.',
    );
  }

  const plist = fs.readFileSync(plistPath, 'utf8');
  const displayNamePattern =
    /(<key>CFBundleDisplayName<\/key>\s*<string>)([^<]*)(<\/string>)/;
  if (!displayNamePattern.test(plist)) {
    throw new Error(
      '[withShareExtensionFix] No CFBundleDisplayName found in ' +
        `${INFO_PLIST_FILE} — update this plugin to match the new template.`,
    );
  }

  fs.writeFileSync(
    plistPath,
    plist.replace(displayNamePattern, `$1${SHARE_SHEET_NAME}$3`),
  );
}

module.exports = withShareExtensionFix;
