const { withXcodeProject } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// This has to be a config plugin (not a one-off manual edit) because
// `ios/` is regenerated by `expo prebuild` on every build.
const TARGET_FILE = 'ShareExtension/ShareViewController.swift';

const PATCHES = [
  {
    // expo-share-intent's generated ShareViewController.swift calls
    // `application.open(url)` to hand off to the host app and *then* calls
    // `extensionContext.completeRequest(...)`. On-device this leaves the
    // calling app (Safari, Chrome, ...) frozen: iOS keeps it suspended
    // until the extension's request is completed, and completing it only
    // *after* kicking off the open() hand-off races the app-switch against
    // the extension process tearing down. Swapping the order — complete
    // first, open second — releases the calling app immediately.
    name: 'complete-request-before-open',
    oldBlock: `    while responder != nil {
      if let application = responder as? UIApplication {
        if application.canOpenURL(url) {
          application.open(url)
        } else {
          NSLog("redirectToHostApp canOpenURL KO: \\(shareProtocol)")
          self.dismissWithError(
            message: "Application not found, invalid url scheme \\(shareProtocol)")
          return
        }
      }
      responder = responder!.next
    }
    extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
  }`,
    newBlock: `    var hostApplication: UIApplication?
    while responder != nil {
      if let application = responder as? UIApplication {
        hostApplication = application
        break
      }
      responder = responder!.next
    }

    guard let application = hostApplication, application.canOpenURL(url) else {
      NSLog("redirectToHostApp canOpenURL KO: \\(shareProtocol)")
      self.dismissWithError(
        message: "Application not found, invalid url scheme \\(shareProtocol)")
      return
    }

    // Release the calling app (Safari/Chrome/...) immediately, *before*
    // asking iOS to open the host app — see the comment above for why the
    // order matters.
    extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
    application.open(url)
  }`,
  },
  {
    // Some apps (WhatsApp's forward arrow, Notes, Mail) hand a shared
    // message to the extension via `NSExtensionItem.attributedContentText`
    // with an *empty* `attachments` array, instead of an item conforming to
    // `public.text`/`public.plain-text`/`public.utf8-plain-text`. The
    // upstream template only ever looks at `attachments`, so those shares
    // silently do nothing — the extension just sits there. This adds a
    // fallback that reads `attributedContentText` when there are no
    // conforming attachments to inspect.
    name: 'attributed-content-text-fallback',
    oldBlock: `      else {
        dismissWithError(message: "No content found")
        return
      }
      for (index, attachment) in (attachments).enumerated() {`,
    newBlock: `      else {
        dismissWithError(message: "No content found")
        return
      }

      if attachments.isEmpty, let plainText = content.attributedContentText?.string,
        !plainText.isEmpty
      {
        // Must hop onto the main actor before doing any of this: the
        // enclosing Task is not main-actor isolated, and redirectToHostApp
        // walks the responder chain and calls canOpenURL/completeRequest/open
        // — all UIKit, all main-thread-only. Running it off-thread crashes
        // the app that presented the share sheet (WhatsApp). Every other
        // handler in this file hops first for exactly this reason; see
        // handleText.
        Task { @MainActor in
          self.sharedText.append(plainText)
          let userDefaults = UserDefaults(suiteName: self.hostAppGroupIdentifier)
          userDefaults?.set(self.sharedText, forKey: self.sharedKey)
          userDefaults?.synchronize()
          self.redirectToHostApp(type: .text)
        }
        return
      }

      for (index, attachment) in (attachments).enumerated() {`,
  },
];

// expo-share-intent writes ShareViewController.swift from a `withXcodeProject`
// mod, not a `withDangerousMod` — those run in a different, earlier phase of
// the prebuild pipeline, so a dangerousMod here would run *before* the file
// even exists. Using the same mod type, registered after expo-share-intent
// in app.json's plugin list, guarantees this runs afterward instead.
function withShareExtensionFix(config) {
  return withXcodeProject(config, async (config) => {
    const filePath = path.join(config.modRequest.platformProjectRoot, TARGET_FILE);
    if (!fs.existsSync(filePath)) {
      throw new Error(
        `[withShareExtensionFix] Expected file not found: ${filePath}. Did expo-share-intent's ` +
          'generated file layout change? Update this plugin to match.',
      );
    }

    let source = fs.readFileSync(filePath, 'utf8');

    for (const patch of PATCHES) {
      if (source.includes(patch.newBlock)) {
        continue; // already patched (e.g. prebuild ran twice)
      }
      if (!source.includes(patch.oldBlock)) {
        throw new Error(
          `[withShareExtensionFix] Patch "${patch.name}" could not find its expected source in ` +
            `${TARGET_FILE} — expo-share-intent's template likely changed. Update ` +
            'plugins/withShareExtensionFix.js to match the new source before this fix can apply.',
        );
      }
      source = source.replace(patch.oldBlock, patch.newBlock);
    }

    fs.writeFileSync(filePath, source);
    return config;
  });
}

module.exports = withShareExtensionFix;
